class UserAlreadyExist(Exception):
    pass


class ValidationError(Exception):
    pass
